feat: Mint and Redeem events emit the updated account balance
VenusProtocol/isolated-pools pull request #144
Opened 2023-01-24 23:40 UTC by gleiser-oliveira

## Description

This PR aims to make the Mint and Redeem VToken events also return the updated value for the account balance. This can make the subgraph save calling the `balanceOf` function everytime it indexes these events.

2023-01-25 18:32 UTC, chechu commented on tests/hardhat/Tokens/mintAndRedeemTest.ts
>        expect(result) // eslint-disable-line @typescript-eslint/no-floating-promises
We need `await` here. Otherwise no errors will be triggered

2023-01-25 18:32 UTC, chechu commented on tests/hardhat/Tokens/mintAndRedeemTest.ts
> +        .withArgs(minterAddress, mintAmount, mintTokens, mintAmount);
Assuming the initial balance of vTokens for the user was 0, the last argument of the event will be `minTokens` (the updated balance of vTokens)

2023-01-25 20:57 UTC, chechu approved these changes

2023-01-26 11:47 UTC, 0xlucian requested changes

2023-01-26 11:47 UTC, 0xlucian commented on contracts/VToken.sol
> +        emit Redeem(redeemer, redeemAmount, redeemTokens, accountTokens[redeemer]);
Reading from storage uses alot of gas. Would be more gas efficient if we do something like:
```
uint256 balanceAfter = accountTokens[redeemer] - redeemTokens;
accountTokens[redeemer] = balanceAfter;
emit Redeem(redeemer, redeemAmount, redeemTokens, balanceAfter);
```

2023-01-26 13:49 UTC, 0xlucian approved these changes

2023-01-26 14:36 UTC, chechu approved these changes

2023-01-26 14:39 UTC, narayanprusty approved these changes

2023-01-26 14:42 UTC, merged