feat: add reward totals to events
VenusProtocol/isolated-pools pull request #147
Opened 2023-01-25 19:46 UTC by coreyar

## Description

Add total rewards available to distribution events

2023-01-25 19:49 UTC, 0xlucian approved these changes

2023-01-25 20:54 UTC, chechu approved these changes

2023-01-26 11:05 UTC, narayanprusty approved these changes

2023-01-26 11:49 UTC, 0xlucian requested changes

2023-01-26 11:49 UTC, 0xlucian commented on contracts/Rewards/RewardsDistributor.sol
> +                rewardTokenAccrued[borrower],
```suggestion
               borrowerAccrued,
```

2023-01-26 13:55 UTC, 0xlucian approved these changes

2023-01-26 13:56 UTC, merged