[VEN-1709]: deploy ankrBNB market in testnet for DeFi Pool
VenusProtocol/isolated-pools pull request #276
Opened 2023-07-14 12:56 UTC by GitGuru7

Resolves VEN-1709]

## Checklist

- [ ] I have updated the documentation to account for the changes in the code.
- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a test preventing this bug from silently reappearing again.
- [ ] My contribution follows [Venus contribution guidelines](docs/CONTRIBUTING.md).

2023-07-17 16:55 UTC, chechu commented on deployments/bsctestnet/VToken_vankrBNB_DeFi.json
the `protocolShareReserve` in the `vankrBNB_DeFi` deployed contract on testnet seems wrong. It should be 0x8b293600c50d6fbdc6ed4251cc75ece29880276f instead of 0x03862dfa5d0be8f64509c001cb8c6188194469df

It should be the VTreasury contract. So, on mainnet it should be 0xf322942f644a996a617bd29c16bd7d231d9f35e9

2023-07-18 11:00 UTC, chechu approved these changes

2023-07-24 04:48 UTC, Debugger022 approved these changes

2023-07-24 10:36 UTC, kkirka requested changes
Can you please run
```
npx hardhat export --network bsctestnet --export ./deployments/bsctestnet.json
npx hardhat export --network bscmainnet --export ./deployments/bscmainnet.json
yarn prettier
git add ./deployments/bsc*.json
git commit -m "feat: export ankrBNB market deployment"
```
?

2023-07-24 12:38 UTC, kkirka approved these changes

2023-07-24 13:03 UTC, chechu approved these changes

2023-07-26 05:22 UTC, merged